// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krgydrmseuoapqketgnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtyZ3lkcm1zZXVvYXBxa2V0Z25mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxMzEyNTMsImV4cCI6MjA2MjcwNzI1M30.waiGYaOjEwfoO16RENXMtpKlw6ofOOOVma-74c08PDg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);